# -*- coding: utf-8 -*-
"""Advertisement_sales_estimation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4-oIiO_J7ZTGR0Et-ULG5yr5ojhhamP

# Advertisement sales estimation Project

About this Project
Problem Statement : This machine learning project going to predict sales prices based on their advertisement spending on different methods ( Radio, TV, Newspaper )
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/machine learning dataset/Advertising Budget and Sales.csv")
df1 = df.drop(['Unnamed: 0'], axis = 'columns')
df1.head()

"""plot data to see which algorithm will fir better"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
from matplotlib import pyplot as plt

plt.scatter(df1['TV Ad Budget ($)'],df1['Sales ($)'])

x = df1.drop(['Sales ($)'], axis = 'columns') 
x.dtypes

y = df1['Sales ($)']
y.head()

"""importing sklearn library """

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size = 0.2)

from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(x_train,y_train)

model.score(x_test,y_test)

model.predict([[15,25,36]])